FF

diff --git a/.github/workflows/hotfix.yaml b/.github/workflows/hotfix.yaml
--- a/.github/workflows/hotfix.yaml
+++ b/.github/workflows/hotfix.yaml
@@ -117,6 +117,8 @@ jobs:
           
           # Push the new branch ------ HEEEREEEE -------
 
+      
+
           is_cherry_pick_success=false
 
           if git cherry-pick "$mergeCommitSha"; then
@@ -125,25 +127,39 @@ jobs:
           else
             echo "❌ Conflict detected. Aborting cherry-pick..."
             git cherry-pick --abort
+          fi
 
-            git commit --allow-empty -m "We have conflicts when cherry-picking the commit: $mergeCommitSha"
+          git cherry-pick "$mergeCommitSha" || true
+
+          if is_cherry_pick_success; then
+            echo "✅ Cherry-pick succeeded. Pushing..."
+          else
+            echo "❌ Conflict detected. Aborting cherry-pick..."
+            git add .
+            git commit -m "We have conflicts when cherry-picking the commit: $mergeCommitSha"
           fi
 
           git push origin $hotfix_branch
           
           echo "hotfix_branch=$hotfix_branch" >> $GITHUB_OUTPUT
           echo "is_cherry_pick_success=$is_cherry_pick_success" >> $GITHUB_OUTPUT
+          echo "mergeCommitSha=$mergeCommitSha" >> $GITHUB_OUTPUT
 
       - name: Create PR
         uses: actions/github-script@v7
         with:
           script: |
             const isCherryPickSuccess = "${{ steps.squash.outputs.is_cherry_pick_success }}" === "true";
+            const mergeCommitSha = "${{ steps.squash.outputs.mergeCommitSha }}";
 
             const title = `New branch from ${{ steps.patch.outputs.latest_patch_branch }}`;
             const head = "${{ steps.squash.outputs.hotfix_branch }}";
             const base = "${{ steps.patch.outputs.latest_patch_branch }}";
-            const body = "This PR was created automatically from the patch branch";
+            const labels = isCherryPickSuccess ? ['deploy-hotfix'] : ['deploy-hotfix', 'deploy-conflict'];
+
+            const body = isCherryPickSuccess ? 
+              'This PR was created automatically from the patch branch' : 
+              `This PR was created automatically from the patch branch, but there were conflicts when cherry-picking the commit: ${mergeCommitSha}`;
 
             const pr = await github.rest.pulls.create({
               owner: context.repo.owner,
@@ -151,23 +167,13 @@ jobs:
               title,
               head,
               base,
-              body
-            });
-
-            const labels = isCherryPickSuccess ? ['deploy-hotfix'] : ['deploy-hotfix', 'deploy-conflict'];
-
-            await github.rest.issues.addLabels({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: pr.data.number,
+              body,
               labels
             });
   
       - name: Show squashed commit
         run: |
           git show ${{ steps.squash.outputs.commit_sha }}
-
-
 
       # - name: Ensure labels exist
       #   uses: actions/github-script@v7
